services:
  real-estate-client:
    container_name: real-estate-client
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - VITE_API_BASE_URL=${VITE_API_BASE_URL}
        - VITE_UPLOAD_API_BASE_URL=${VITE_UPLOAD_API_BASE_URL}
    ports:
      - '5173:80'
    env_file:
      - .env
    networks:
      - real-estate-network

networks:
  real-estate-network:
    external: true
